hw:
  ui:
    locale: en
    acceptable-locale:
      - en

spring:
  datasource:
    url: 'jdbc:h2:mem:library'
  shell:
    interactive:
      enabled: false
    command:
      script:
        enabled: false

logging:
  level:
    root: error